Add Word Quiz Function
dnd-side-project/dnd-11th-10-backend pull request #71
Opened 2024-08-19 11:51 UTC by miraexhoi

## 📎 관련 Issue 번호
- closes #51 

## 📄 작업 내용 요약
용어 퀴즈 기능 추가
- 용어 테스트 생성
- 용어 테스트 시작
- 용어 테스트 정답 제출

## 🙋🏻 주의 깊게 확인해야 하는 코드
매핑 부분 주의 깊게 확인 부탁드려요!

## 📄 개선 사항 OR 참고 사항
이후 추가적으로 카테고리별 업무 능력치 백분율 구현하도록 하겠습니다 ~

2024-08-19 15:00 UTC, apptie commented on src/main/java/com/dnd/spaced/domain/quiz/application/QuizService.java
> +    }
## 질문 💬

Collections.shuffle(questions) 호출로 인해서 별도의 메서드로 분리하고, stream을 통해 새롭게 컬렉션을 만들고 있는데 

```java
public QuizResponseDto generateQuiz(QuizRequestDto requestDto) {
    Category category = findCategoryByName(requestDto.categoryName());
    List<QuizQuestion> questions = findQuestionsByCategory(category.getName());
    validateQuestionCount(questions);
    Collections.shuffle(questions);
    Long quizId = saveQuiz(questions);

    return QuizServiceMapper.toResponse(quizId, selectedQuestions);
}
```

이렇게 하지 않고 별도의 메서드로 분리하고, stream을 사용한 이유가 궁금합니다

2024-08-19 15:07 UTC, apptie commented on src/main/java/com/dnd/spaced/domain/quiz/application/QuizService.java
> +        return quiz.getId();
## 필수 🚨

```suggestion
        return quiz.getId()
```

CrudRepository.save()에서 메서드 파라미터로 지정된 도메인에 id는 자동 할당되므로 재할당할 필요는 없습니다

```suggestion
        return quizCrudRepository.save(quiz).getId()
```


CrudRepository.save()의 반환 값을 사용하고자 한다면 별도로 할당하지 않고 바로 접근해주세요

2024-08-19 15:11 UTC, apptie commented on src/main/java/com/dnd/spaced/domain/quiz/application/QuizService.java
> +        List<QuizQuestion> questions = findQuestionsByCategory(category.getName());
## 질문 💬

findQuestionsByCategory()에서 조회되는 QuizQuestion은 어디에서 생성되나요? 
QuerydslQuizRepository에서도 딱히 저장하는 부분이 없고, QuizQuestionCrudRepository 같은것도 없어서 질문드립니다

2024-08-19 15:18 UTC, apptie commented on src/main/java/com/dnd/spaced/domain/quiz/domain/repository/QuerydslQuizRepository.java
> +                .fetch();
## 질문 💬

해당 메서드가 QuizService.findQuestionsByCategory(String categoryName)로 호출되는 것 같습니다 

생성된 QuizQuestion을 단순히 카테고리 이름(개발, 디자인, 비즈니스, 전체)만으로 where절을 통해 필터링했을 때 QuizService.validateQuestionCount(questions)에서 검증하는 것 처럼 반드시 QuizQuestion이 5개일 수가 있나요?

만약 개발 카테고리로 퀴즈를 세 개 생성한 경우에서도 정상 동작하는게 맞나요?

2024-08-20 00:44 UTC, miraexhoi commented on src/main/java/com/dnd/spaced/domain/word/domain/Category.java
> +    BUSINESS("비즈니스"), DEVELOP("개발"), DESIGN("디자인"), ALL("전체 실무");
음.. 저도 이부분은 헷갈렸습니다
좋은 피드백 감사합니다 Quiz 도메인 용 Category를 생성해서 
Quiz 도메인 서비스 로직에서는 이 Category 를 사용하도록 수정했습니다 [efe61e0](https://github.com/dnd-side-project/dnd-11th-10-backend/pull/71/commits/efe61e0128486d739afc7eb8bd9062197d767660)

2024-08-20 00:47 UTC, miraexhoi commented on src/main/java/com/dnd/spaced/domain/quiz/application/QuizService.java
> +        if (questions.size() < 5) {
수정했습니다 [e2382eb](https://github.com/dnd-side-project/dnd-11th-10-backend/pull/71/commits/e2382ebccf688a386cf42839de801bb980f76baa)

2024-08-20 00:50 UTC, miraexhoi commented on src/main/java/com/dnd/spaced/domain/quiz/application/QuizService.java
> +        return questions.stream().limit(5).collect(Collectors.toList());
https://github.com/dnd-side-project/dnd-11th-10-backend/pull/71#discussion_r1722549349

2024-08-20 01:29 UTC, miraexhoi commented on src/main/java/com/dnd/spaced/domain/quiz/application/QuizService.java
> +    }
1. quizRepository 에서 category 로 question 을 검색하는것 또한 한가지의 책임인걸로 알고 있어서 단일 책임 원칙을 준수하기 위해 분리하였습니다
2. public 은 바로 고치도록 하겠습니다

2024-08-20 02:18 UTC, miraexhoi commented on src/main/java/com/dnd/spaced/domain/quiz/application/QuizService.java
> +    }
넵 적용해서 수정했습니다! [4804e50](https://github.com/dnd-side-project/dnd-11th-10-backend/pull/71/commits/4804e5060b9c3fc75c5e6f49a3fc000e3625afe7)

2024-08-20 03:11 UTC, miraexhoi commented on src/main/java/com/dnd/spaced/domain/quiz/application/QuizService.java
> +                .filter(option -> option.getId().equals(answerId))
음.. 말씀하신 대로 `@EqualsAndHashCode` 사용하도록 수정해봤는데 확인 부탁드려요 [2f36ff4](https://github.com/dnd-side-project/dnd-11th-10-backend/pull/71/commits/2f36ff445ac2544ede2a7a66f760c7d015cd9b72)

2024-08-20 03:13 UTC, miraexhoi commented on src/main/java/com/dnd/spaced/domain/quiz/application/QuizService.java
> +                .filter(option -> option.getId().equals(answerId))
말씀하신대로 수정해봤는데 확인 부탁드려요 [67a129e](https://github.com/dnd-side-project/dnd-11th-10-backend/pull/71/commits/67a129ed907dfb0a6aca6ad4344ffa64fb591d5b)

2024-08-20 03:17 UTC, miraexhoi commented on src/main/java/com/dnd/spaced/domain/quiz/domain/Quiz.java
> +public class Quiz {
완료 했습니다 [cc3cad0](https://github.com/dnd-side-project/dnd-11th-10-backend/pull/71/commits/cc3cad03bb0b78e2a243b1725e9b8924d855fa34)

2024-08-20 03:24 UTC, miraexhoi commented on src/main/java/com/dnd/spaced/domain/quiz/presentation/QuizController.java
> +    public ResponseEntity<QuizResponse> createQuiz(@RequestBody QuizRequest request) {
제가 놓친 부분인거 같습니다 `@valid` 추가했습니다 [4f0a7bc](https://github.com/dnd-side-project/dnd-11th-10-backend/pull/71/commits/4f0a7bcd792a95df81f3a92f68da711bc6fb1c89)

2024-08-20 03:29 UTC, miraexhoi commented on src/main/java/com/dnd/spaced/domain/quiz/application/QuizService.java
> +    }
Collections.shuffle()을 사용하여 질문 목록을 섞고, Stream을 통해 새로운 리스트를 생성하는 방식을 
별도의 메서드로 분리하여 책임을 명확하게 하고자 했습니다

2024-08-20 03:32 UTC, miraexhoi commented on src/main/java/com/dnd/spaced/domain/quiz/application/QuizService.java
> +        List<QuizQuestion> questions = findQuestionsByCategory(category.getName());
QuizQuestion 자체를 생성하는 로직은 어드민에서 관리되고 있는걸로 알고 있는데 이부분에 대해 질문 주신게 맞을까요?

2024-08-20 03:34 UTC, miraexhoi commented on src/main/java/com/dnd/spaced/domain/quiz/domain/repository/QuerydslQuizRepository.java
> +                .fetch();
`findQuestionsByCategory` 메서드는 카테고리에 따라 기존 데이터베이스에서 `QuizQuestion` 을 조회합니다. 
만약 해당 카테고리에 5개 미만의 질문이 있다면, `QuizService.validateQuestionCount` 에서 예외를 발생시킵니다.

2024-08-20 03:45 UTC, apptie commented on src/main/java/com/dnd/spaced/domain/quiz/application/QuizService.java
> +        List<QuizQuestion> questions = findQuestionsByCategory(category.getName());
네 맞습니다 

QuizQuestion을 관리자 기능으로 관리하는 거였나요? 전 랜덤으로 만드는걸로 인지하고 있었습니다 
뭐 관리자 기능도 미래님께서 담당하시니 큰 상관은 없을 것 같네요

2024-08-20 03:46 UTC, apptie commented on src/main/java/com/dnd/spaced/domain/quiz/domain/repository/QuerydslQuizRepository.java
> +                .fetch();
위에 QuizQuestion을 관리자 기능으로 구현한다고 하신 내용을 보니 이해가 되네요

2024-08-20 03:49 UTC, apptie commented on src/main/java/com/dnd/spaced/domain/quiz/application/QuizService.java
> +                .filter(option -> option.getId().equals(answerId))
`@EqualsAndHashCode`는 제대로 설정해주셨는데 다른게 문제였네요 
수정된 코드에서 리뷰 남기도록 하겠습니다

2024-08-20 04:23 UTC, apptie requested changes
고생하셨습니다

자잘한 부분만 추가적으로 수정해주시면 될 것 같습니다 

추가적으로 Resolve conversation은 일반적으로 리뷰어가 처리합니다 
리뷰이가 남긴 댓글 등을 확인하려면 하나하나 Show resolved를 클릭해서 확인해야 하기 때문에 리뷰어 입장에서는 혼란스러울 수 있기 때문입니다

2024-08-20 04:23 UTC, apptie commented on src/main/java/com/dnd/spaced/domain/quiz/application/QuizService.java
> +    }
저는 다른 부분도 단일 책임 원칙을 너무 과하게 적용해서 가독성 및 유지보수가 떨어진다고 생각하고 있습니다 
https://github.com/dnd-side-project/dnd-11th-10-backend/pull/71#discussion_r1721932498 에도 적용되는 부분인데, 해당 메서드가 재사용되지 않고 메서드 내부에 단순 by-pass로 호출하고 있으므로 불필요한 추상화 계층을 만들었다고 생각하기 때문입니다

확장성을 고려했다면 이해가 안되지는 않지만, YAGNI 원칙에 위배되기 때문에 확장성을 위해 얻는 장점보다는 단점이 더 크다고 생각합니다 
실제로 제가 QuizService.generateQuiz()를 리뷰하기 위해서 다섯 개의 메서드를 하나하나 찾아가야 했기 때문에 가독성이 상당히 떨어졌다고 느꼈습니다 
추후 해당 코드를 수정해야 한다면 QuizService.generateQuiz() 메서드 하나가 아니라, 5개의 메서드를 수정해야 한다는 불편함도 생기지 않을까 싶기도 합니다  

그래도 다른 부분은 로직이 복잡해서 별도로 메서드로 묶을만하거나, 성능에 저하가 있지는 않으니 납득할 수는 있는데 QuizService.selectRandomQuestions() 메서드는 과도하게 책임을 분리했기 때문에 성능이 저하되서 좋은 코드는 아니라고 생각합니다 
stream을 통한 불필요한 순회와 새로운 컬렉션이 생성되었기 때문입니다 
물론 크기가 5개밖에 없으니 엄밀히 따지자면 큰 상관은 없겠지만 불필요한 동작이기는 하니까요

미래님께서 말씀하시고 진행하신대로 정말 작은 단위로 책임을 쪼갠다면 질문 목록을 섞는 것도 하나의 책임이라고 보고 지금처럼 분리할 수도 있을 것입니다
하지만 QuizService 입장에서 보자면 generateQuiz()의 내부 코드를 엄격하게 작은 책임으로 쪼개서 과도한, 불필요한 추상화로 인해 문맥이 훼손될 수 있는 등 장단점을 고려해보시는 것도 좋을 것 같습니다

물론 동작은 하니까 굳이 수정하실 필요는 없을 것 같습니다

2024-08-20 04:23 UTC, apptie commented on src/main/java/com/dnd/spaced/domain/quiz/application/QuizService.java
> +        return questions.stream().limit(MIN_QUESTION_SIZE).collect(Collectors.toList());
## 필수 🚨

```suggestion
        return questions.stream().limit(MIN_QUESTION_SIZE).toList();
```

2024-08-20 05:23 UTC, miraexhoi commented on src/main/java/com/dnd/spaced/domain/quiz/presentation/dto/request/QuizRequest.java
> +        List<Long> answerIds
넵 추가 했습니다 ~ [d39092a](https://github.com/dnd-side-project/dnd-11th-10-backend/pull/71/commits/d39092a46d5eb4b7a64ffc710839a0ef6c683f53)

2024-08-20 05:25 UTC, miraexhoi commented on src/main/java/com/dnd/spaced/domain/quiz/application/QuizService.java
> +        return questions.stream().limit(MIN_QUESTION_SIZE).collect(Collectors.toList());
수정했습니다 [6962037](https://github.com/dnd-side-project/dnd-11th-10-backend/pull/71/commits/6962037359efc8f847e92f2efc63c0dae7bb4405)

2024-08-20 05:33 UTC, miraexhoi commented on src/main/java/com/dnd/spaced/domain/quiz/application/QuizService.java
> +    }
수정해 봤는데 확인 부탁 드릴게요 [e77ed8c](https://github.com/dnd-side-project/dnd-11th-10-backend/pull/71/commits/e77ed8c0e7a0529a6ff130567f97743953b4642b)

2024-08-20 06:16 UTC, apptie requested changes
고생하셨습니다
하나만 더 수정하면 될 것 같습니다

2024-08-20 06:16 UTC, apptie commented on src/main/java/com/dnd/spaced/domain/quiz/domain/QuizQuestion.java
> +    }
## 필수 🚨

QuizQuestion에서 getOptionById()를 통해 QuizOption을 외부인 QuizService에 노출하지 않는 것은 깔끔하게 개선이 된 것 같습니다 

다만 option.getId()가 여전히 남아 있네요 
이건 이전에 제 리뷰인

> 해당 부분은 QuizQuestion.getOptions()로 꺼낸 뒤, 이걸 stream으로 순회하면서 option.getId()를 꺼내서 answerId와 비교해 사용자가 입력한 정답을 QuizOption으로 치환하는 코드로 이해했습니다

여기서 `QuizQuestion.getOptions()로 꺼낸 뒤 사용자가 입력한 정답을 QuizOption으로 치환` 까지는 적용되었으나 `option.getId()를 꺼내서 answerId와 비교`는 여전히 디미터 법칙을 위반하고 있습니다 

answerId와 option의 id가 동일한지 여부는 QuizOption의 책임이지, QuizQuestion에서 QuizOption.getId()로 꺼내서 직접 비교하는 것은 객체지향적으로 바람직하지 않다고 생각합니다 

QuizOption에 answerId를 전달해서, QuizOption의 id와 answerId가 일치하는지 여부를 boolean으로 반환하는 메서드를 추가해서 처리해주시면 될 것 같습니다

2024-08-20 06:49 UTC, miraexhoi commented on src/main/java/com/dnd/spaced/domain/quiz/domain/QuizQuestion.java
> +    }
넵 수정했습니다 [2a912b8](https://github.com/dnd-side-project/dnd-11th-10-backend/pull/71/commits/2a912b8617f06c6696061de1194705d3cd2c83a2)

2024-08-20 07:01 UTC, apptie approved these changes
고생하셨습니다

2024-08-20 07:01 UTC, apptie commented on src/main/java/com/dnd/spaced/domain/quiz/domain/Category.java
> +        return Arrays.stream(com.dnd.spaced.domain.quiz.domain.Category.values())
## 질문 💬

왜 FQCN을 사용하셨나요?

2024-08-20 07:05 UTC, miraexhoi commented on src/main/java/com/dnd/spaced/domain/quiz/domain/Category.java
> +        return Arrays.stream(com.dnd.spaced.domain.quiz.domain.Category.values())
흠 카테고리 enum 클래스가 두개라 아마 임포트 될때 자동으로 추가된거 같습니다.. 
일단은 가독성을 위해 수정해 두겠습니다 [c95bbfb](https://github.com/dnd-side-project/dnd-11th-10-backend/pull/71/commits/c95bbfb180a04a6f5b07845524ff4a41c61552d2)

2024-08-20 07:09 UTC, apptie approved these changes

2024-08-20 07:10 UTC, merged